### ISSUE TITLE
Quicktime linking to wrong architecture

### ISSUE THREAD

**Issue by peterkolski** [BildPeter/ofxCMake#3]
In ofxAssimpModelLoader, ofxOpenCV:

`ld: warning: ignoring file /System/Library/Frameworks//QuickTime.framework/QuickTime, file was built for i386 which is not the architecture being linked (x86_64): /System/Library/Frameworks//QuickTime.framework/QuickTime`

**Comment by symbolix** [comment]
I remember to get the same thing, I think it is even there when you do an Xcode build. However, in my tests, things did not break because of this.

**Comment by peterkolski** [comment]
You are totally right. That was not the issue. The osx Libs provided by OF are not linked correctly. So ofxKinect, ofxAssimpModelLoader and ofxOpenCV are not working yet
