### ISSUE TITLE
installation path need to be clarified

### ISSUE THREAD

**Issue by avilleret** [BildPeter/ofxCMake#5]
from the Readme.md : 

> 1. Create there a subfolder CMake
> 2. Clone or extract the git files and folders into this folder.

But if I'm doing : 

```
$ cd of
$ mkdir CMake 
$ cd CMake 
$ git clone https://github.com/BildPeter/ofxCMake.git
```

I will have this folder structure : 

```
CMake/
└── ofxCMake
    ├── addOns
    │   ...
    ├── libs
    │   ...
    ├── modules
    │   ...
    ├── ofxCMake_Logo.jpg
    ├── project
    │   └── CMakeLists.txt
    └── README.md
```

while this seems to be expected by CMakelists.txt :

```
CMake/
├── addOns
│   ...
├── libs
│   ...
├── modules
│   ...
├── ofxCMake_Logo.jpg
├── project
│   └── CMakeLists.txt
└── README.md
```

So the command line should be : 

```
$ cd of
$ git clone https://github.com/BildPeter/ofxCMake.git CMake
```

That's all.

Maybe you can update the Readme.md ?
I don't know which tool your are using to clone.

**Comment by peterkolski** [comment]
Hey Thanks!
I updated the README – if you think the new explanation is sufficient, I will close the issue.

**Comment by avilleret** [comment]
You don't need the `mkdir` step since `git` will create the directory for you.
The most straightforward way to use your project would have been to just clone the repo inside the of folder (without any extra encapsulation).
But this requires to changes all paths where "/CMake/" appears to "/ofxCMake/" which may be not desirable...

**Comment by peterkolski** [comment]
I think it might not be a too bad idea to actually leave the name ofxCMake and just put it into the addons folder, as for a 'normal' user, the workflow stays the same for installing other AddOns. In this case, I would change the paths. 

Down side would be, that in the future it might have a conflict with other addOns. I planned to just scan all AddOns for .cmake configuration files. Then the addOns are automatically included. But for now, this is not the case, as it would be needed to copy the .cmake files into the addOn folders.

**Comment by avilleret** [comment]
Concerning the possible conflict with other addons, I think it is pretty convenient to exclude ofxCMake from the addons list to process and if another addon have the same name, it is probably  doing the same, and thus will be redundant.

**Comment by peterkolski** [comment]
I changed it to a simple ofxCMake path in the addons. Then the installation is easier.

NOTE:
- Clone it into the addons
- if you use the old CMakeLists.txt in your project, then you have to change the path in there:
  `include( ${OF_DIRECTORY_BY_USER}/addons/ofxCMake/modules/main.cmake )`
